job('HelloWorld-Project-via-DSL'){
    description("First Maven project job generated by the DSL on ${new Date()}, hoste on github")
    scm{
        git("https://github.com/mishobo/jenkins-test.git", 'main')
    }
    triggers{
        scm('* * * * *')
    }
    steps{
        maven('clean package', 'pom.xml')
    }
    publishers{
        //archive the war file generated
        archiveArtifacts '**/*.war'
    }
}
